
INSERT INTO bid_app_user VALUES ('admin','1','America',0,'1991-11-04','godov@freemail.hu','male','admin'  );
INSERT INTO event(description,end_date,event_type,start_date) VALUES ( 'Lotto 5 sorsolas','2022-08-11',1,'2022-08-11');
--create table participant (participant_id integer generated by default as identity, event_type varchar(255), name varchar(255), primary key (participant_id));
INSERT INTO participant(sport_type,name) VALUES (1,'Soros Gyorgy');