
INSERT INTO bid_app_user VALUES ('admin','1','America',0,'1991-11-04','godov@freemail.hu','male','admin'  );
--create table event (event_id integer generated by default as identity, description varchar(255), end_date date, event_type integer, start_date date, primary key (event_id));
INSERT INTO event(description,end_date,event_type,start_date) VALUES ( 'Lotto 5 sorsolas','2022-08-11',1,'2022-08-11');