drop table if exists bid CASCADE;
drop table if exists bid_app_user CASCADE;
drop table if exists bid_lotto5 CASCADE;
drop table if exists bid_lotto6 CASCADE;
drop table if exists bid_scandinavian CASCADE;
drop table if exists event CASCADE;
drop table if exists lotto5 CASCADE;
drop table if exists lotto6 CASCADE;
drop table if exists participant CASCADE;
drop table if exists scandinavian CASCADE;
drop table if exists sport_bid CASCADE;
drop table if exists sport_event CASCADE;
drop table if exists sport_participant CASCADE;
create table bid
(
    bid_id     integer generated by default as identity,
    bid_amount bigint not null,
    bid_type   varchar(255),
    date       date,
    prize      bigint not null,
    event_id   integer,
    username   varchar(255),
    primary key (bid_id)
);
create table bid_app_user
(
    username      varchar(255) not null,
    account_level integer      not null,
    address       varchar(255),
    balance       bigint       not null,
    birth_date    date,
    email         varchar(255),
    gender        varchar(255),
    password      varchar(255),
    primary key (username)
);
create table bid_lotto5
(
    bid_id  integer not null,
    matches integer not null,
    number1 integer not null,
    number2 integer not null,
    number3 integer not null,
    number4 integer not null,
    number5 integer not null,
    primary key (bid_id)
);
create table bid_lotto6
(
    bid_id  integer not null,
    matches integer not null,
    number1 integer not null,
    number2 integer not null,
    number3 integer not null,
    number4 integer not null,
    number5 integer not null,
    number6 integer not null,
    primary key (bid_id)
);
create table bid_scandinavian
(
    bid_id           integer not null,
    computer_number1 integer not null,
    computer_number2 integer not null,
    computer_number3 integer not null,
    computer_number4 integer not null,
    computer_number5 integer not null,
    computer_number6 integer not null,
    computer_number7 integer not null,
    matches          integer not null,
    matches_computer integer not null,
    number1          integer not null,
    number2          integer not null,
    number3          integer not null,
    number4          integer not null,
    number5          integer not null,
    number6          integer not null,
    number7          integer not null,
    primary key (bid_id)
);
create table event
(
    event_id    integer generated by default as identity,
    description varchar(255),
    end_date    date,
    event_type  integer,
    start_date  date,
    primary key (event_id)
);
create table lotto5
(
    event_id integer not null,
    number1  integer not null,
    number2  integer not null,
    number3  integer not null,
    number4  integer not null,
    number5  integer not null,
    primary key (event_id)
);
create table lotto6
(
    event_id integer not null,
    number1  integer not null,
    number2  integer not null,
    number3  integer not null,
    number4  integer not null,
    number5  integer not null,
    number6  integer not null,
    primary key (event_id)
);
create table participant
(
    participant_id integer generated by default as identity,
    sport_type     integer,
    name           varchar(255),
    primary key (participant_id)
);
create table scandinavian
(
    event_id         integer not null,
    computer_number1 integer not null,
    computer_number2 integer not null,
    computer_number3 integer not null,
    computer_number4 integer not null,
    computer_number5 integer not null,
    computer_number6 integer not null,
    computer_number7 integer not null,
    number1          integer not null,
    number2          integer not null,
    number3          integer not null,
    number4          integer not null,
    number5          integer not null,
    number6          integer not null,
    number7          integer not null,
    primary key (event_id)
);
create table sport_bid
(
    sport_bid_id   integer not null,
    bid_id         integer,
    participant_id integer,
    primary key (sport_bid_id)
);
create table sport_event
(
    event_id   integer not null,
    sport_type integer,
    winner_id  integer,
    primary key (event_id)
);
create table sport_participant
(
    id             integer not null,
    multiplier     integer not null,
    event_id       integer,
    participant_id integer,
    primary key (id)
);
alter table bid
    add constraint fk_user_bid_event foreign key (event_id) references event;
alter table bid
    add constraint fk_user_bid foreign key (username) references bid_app_user;
alter table sport_bid
    add constraint fk_sportBid_bid foreign key (bid_id) references bid;
alter table sport_bid
    add constraint fk_BidTo_participant foreign key (participant_id) references participant;
alter table sport_event
    add constraint fk_sport_event_winner foreign key (winner_id) references sport_participant;
alter table sport_participant
    add constraint fk_sportEvent_sportParticipant foreign key (event_id) references sport_event;
alter table sport_participant
    add constraint fk_sportEvent_participant foreign key (participant_id) references participant;