drop table if exists bid_app_user CASCADE;
drop table if exists event CASCADE;
drop table if exists participant CASCADE;


create table bid_app_user
(
    username      varchar(255) not null,
    account_level integer      not null,
    address       varchar(255),
    balance       bigint       not null,
    birth_date    date,
    email         varchar(255),
    gender        varchar(255),
    password      varchar(255),
    primary key (username)
);

create table participant
(
    participant_id integer generated by default as identity,
    sport_type     integer,
    name           varchar(255),
    primary key (participant_id)
);
create table event
(
    event_id    integer generated by default as identity,
    description varchar(255),
    end_date    date,
    event_type  integer,
    start_date  date,
    primary key (event_id)
);