drop table if exists bid CASCADE;
drop table if exists bid_lotto5 CASCADE;
drop table if exists bid_lotto6 CASCADE;
drop table if exists bid_scandinavian CASCADE;
drop table if exists lotto5 CASCADE;
drop table if exists lotto6 CASCADE;
drop table if exists scandinavian CASCADE;


create table bid
(
    bid_id     integer generated by default as identity,
    bid_amount bigint not null,
    bid_type   varchar(255),
    date       date,
    prize      bigint not null,
    event_id   integer,
    username   varchar(255),
    primary key (bid_id)
);
create table bid_lotto5
(
    bid_id  integer not null,
    matches integer not null,
    number1 integer not null,
    number2 integer not null,
    number3 integer not null,
    number4 integer not null,
    number5 integer not null,
    primary key (bid_id)
);
create table bid_lotto6
(
    bid_id  integer not null,
    matches integer not null,
    number1 integer not null,
    number2 integer not null,
    number3 integer not null,
    number4 integer not null,
    number5 integer not null,
    number6 integer not null,
    primary key (bid_id)
);
create table bid_scandinavian
(
    bid_id           integer not null,
    computer_number1 integer not null,
    computer_number2 integer not null,
    computer_number3 integer not null,
    computer_number4 integer not null,
    computer_number5 integer not null,
    computer_number6 integer not null,
    computer_number7 integer not null,
    matches          integer not null,
    matches_computer integer not null,
    number1          integer not null,
    number2          integer not null,
    number3          integer not null,
    number4          integer not null,
    number5          integer not null,
    number6          integer not null,
    number7          integer not null,
    primary key (bid_id)
);

create table lotto5
(
    event_id integer not null,
    number1  integer not null,
    number2  integer not null,
    number3  integer not null,
    number4  integer not null,
    number5  integer not null,
    primary key (event_id)
);
create table lotto6
(
    event_id integer not null,
    number1  integer not null,
    number2  integer not null,
    number3  integer not null,
    number4  integer not null,
    number5  integer not null,
    number6  integer not null,
    primary key (event_id)
);
create table scandinavian
(
    event_id         integer not null,
    computer_number1 integer not null,
    computer_number2 integer not null,
    computer_number3 integer not null,
    computer_number4 integer not null,
    computer_number5 integer not null,
    computer_number6 integer not null,
    computer_number7 integer not null,
    number1          integer not null,
    number2          integer not null,
    number3          integer not null,
    number4          integer not null,
    number5          integer not null,
    number6          integer not null,
    number7          integer not null,
    primary key (event_id)
);
alter table bid
    add constraint fk_user_bid_event foreign key (event_id) references event;
alter table bid
    add constraint fk_user_bid foreign key (username) references bid_app_user;